spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - name: AuthFilter

        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/sale/**
          filters:
            - name: AuthFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: AuthFilter

        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/report/**
          filters:
            - name: AuthFilter

        - id: security
          uri: lb://security
          predicates:
            - Path=/login
          filters:
              - RewritePath=/login,/auth/login


      discovery:
        locator:
          enabled: true

server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:log4j2-spring.xml
